//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarSkills
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationStatus
    {
        public byte RegistrationStatusId { get; set; }
        public string RegistrationStatus1 { get; set; }
    }
}
